[package]
name = "lego_robot"
version = "0.1.0"
edition = "2021"

[dependencies]
ev3dev-lang-rust = "0.10.2"
actix-web = "3.3.2"
actix-files = "0.5.0"
serde = "1.0.130"
serde_json = "1.0.74"
glob = "0.3.0"
base64 = "0.13.0"
image = "0.23.14"

[profile.release]
lto = true